CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO users (name, email)
VALUES
('Ana Silva', 'ana.silva@example.com'),
('Bruno Costa', 'bruno.costa@example.com'),
('Carla Pereira', 'carla.pereira@example.com'),
('Daniel Souza', 'daniel.souza@example.com'),
('Elisa Martins', 'elisa.martins@example.com'),
('Felipe Rocha', 'felipe.rocha@example.com'),
('Gabriela Alves', 'gabriela.alves@example.com'),
('Henrique Lima', 'henrique.lima@example.com'),
('Isabela Fernandes', 'isabela.fernandes@example.com'),
('João Oliveira', 'joao.oliveira@example.com'),
('Karina Dias', 'karina.dias@example.com'),
('Lucas Ferreira', 'lucas.ferreira@example.com'),
('Mariana Gomes', 'mariana.gomes@example.com'),
('Nathan Silva', 'nathan.silva@example.com'),
('Olívia Ramos', 'olivia.ramos@example.com'),
('Paulo Barros', 'paulo.barros@example.com'),
('Quésia Nunes', 'quesia.nunes@example.com'),
('Ricardo Mendes', 'ricardo.mendes@example.com'),
('Sabrina Pinto', 'sabrina.pinto@example.com'),
('Thiago Cunha', 'thiago.cunha@example.com'),
('Úrsula Castro', 'ursula.castro@example.com'),
('Vitor Moreira', 'vitor.moreira@example.com'),
('Wesley Santos', 'wesley.santos@example.com'),
('Xênia Cardoso', 'xenia.cardoso@example.com'),
('Yasmin Freitas', 'yasmin.freitas@example.com'),
('Zeca Vieira', 'zeca.vieira@example.com'),
('Adriana Lopes', 'adriana.lopes@example.com'),
('Bruno Nascimento', 'bruno.nascimento@example.com'),
('Camila Ribeiro', 'camila.ribeiro@example.com'),
('Diego Teixeira', 'diego.teixeira@example.com'),
('Eliane Carvalho', 'eliane.carvalho@example.com'),
('Fernando Pacheco', 'fernando.pacheco@example.com'),
('Geovana Araújo', 'geovana.araujo@example.com'),
('Hugo Monteiro', 'hugo.monteiro@example.com'),
('Iara Fernandes', 'iara.fernandes@example.com'),
('Jorge Mendes', 'jorge.mendes@example.com'),
('Kelly Santos', 'kelly.santos@example.com'),
('Leonardo Souza', 'leonardo.souza@example.com'),
('Márcia Almeida', 'marcia.almeida@example.com'),
('Nelson Costa', 'nelson.costa@example.com'),
('Olga Faria', 'olga.faria@example.com'),
('Pedro Lima', 'pedro.lima@example.com'),
('Quintino Lopes', 'quintino.lopes@example.com'),
('Rafaela Oliveira', 'rafaela.oliveira@example.com'),
('Samuel Barbosa', 'samuel.barbosa@example.com'),
('Tatiana Rocha', 'tatiana.rocha@example.com'),
('Ulisses Mendes', 'ulisses.mendes@example.com'),
('Vanessa Souza', 'vanessa.souza@example.com'),
('William Azevedo', 'william.azevedo@example.com'),
('Xavier Martins', 'xavier.martins@example.com');
